### PR TITLE
1Password

### PR DESCRIPTION
**Pull request by tyrann0us**
>1Password 7 for Mac currently runs on M1 using Apple's Rosetta 2 technology but we're excited about the opportunities native support will offer and hope to have more to say on the subject soon.
– https://1password.community/discussion/comment/577134/#Comment_577134

### CODE REVIEW

**Comment by ThatGuySam** [comment]
Thanks for the pull request! 

It’s up: https://doesitarm.com/app/1password/

**Comment by KovalevArtem** [comment]
https://www.reddit.com/r/1Password/comments/jy3ygw/is_1password_working_on_native_support_for_the/

**Comment by KovalevArtem** [comment]
https://blog.1password.com/apple-silicon/

**Comment by ThatGuySam** [comment]
@KovalevArtem Good catch!

Let’s keep any eye on it to see when the full release drops

**Pull request merged**
