### PR TITLE
Added Virtualbox

### PR DESCRIPTION
**Pull request by steve1878**

### CODE REVIEW

**Comment by steve1878** [comment]
Corresponding issue https://github.com/ThatGuySam/doesitarm/issues/33

**Comment by ThatGuySam** [comment]
This one's definitely overdue to be added. 

Never is a pretty strong word. Apps like CrossOver, QEMU, and even Docker have successfully done virtualization on Apple Silicon so far. 

I would say it's not a matter of "if" it can happen but, perhaps, rather if the performance good enough to be useful, however, I could be wrong. 

Do you know of a strong reason why it would be impossible. 

I'm open to new info.

**Comment by steve1878** [comment]
> Do you know of a strong reason why it would be impossible.
> 
> I'm open to new info.

Short answer: You are definitely right. So feel free to change the status to: "🚫 No, not yet supported only works on Intel-based Macs.". 

Long answer: My reason basically is based on the discussion I cite: "VirtualBox can't be ported to an ARM, because it's an x86 hypervisor, not a simulator.". According to the end user documentation of VirtualBox (https://www.virtualbox.org/wiki/End-user_documentation) VirtualBox is meant to support Intel OSes on Intel hardware, that said: natively supporting ARM would be out of scope. However, you are right. That argument only holds for native support. Supporting Apple Silicon using Rosetta might make sense and might be part of future.

**Comment by steve1878** [comment]
> Never is a pretty strong word. Apps like CrossOver, QEMU, and even Docker have successfully done virtualization on Apple Silicon so far.

Just to be complete on similar solutions:

CrossOver (based on Wine): The homepage of wine states (in its first lines, see winehq.org): "Instead of simulating internal Windows logic like a virtual machine or emulator, Wine translates Windows API calls into POSIX calls on-the-fly". Hence, it does not do virtualization and is not the best example here.

QEMU: The homepage of QEMU states (again first line, see qemu.org): "QEMU is a generic and open source machine emulator and virtualizer". In addition to virtualization, emulation of other hardware is in the most narrow scope of the software - which is different to what VirtualBox states as its scope.

Docker: Dockers focus is supporting containers and has therefore supported hosts with non-Intel-hardware for years.

Solutions more similar to VirtualBox are Parallels and VMWare. While Parallels only supports ARM-clients and ARM hosts (https://9to5mac.com/2020/12/17/windows-m1-mac-parallels/), VMWare is "committed to delivering VMware virtual machines on Apple Silicon" for Intel guests (https://blogs.vmware.com/euc/2020/12/apple-m1-chip-how-vmware-makes-it-work-for-the-enterprise.html). In sum, both solutions will support Apple Silicon in the future. 

However, no solution mentioned above has the narrow scope of VirtualBox ("it installs on your existing Intel or AMD-based computers", see https://www.virtualbox.org/manual/ch01.html).

**Comment by ThatGuySam** [comment]
That’s a good point about CrossOver and the Virtualization software. 

While it might be premature to say it won’t ever happen, Oracle/VirtualBox hasn’t made any official statement on it one way or the other since Apple Silicon has become publicly available. 

I think they want to offer a solution for Mac users but don’t want to make any promises yet just in case they can’t find a reasonable way to do it. 

Another possibility is they may release a new separate product that can run on ARM. 

What we can do is keep an eye on the official communication channels for VirtualBox and if they make a statement about it we’ll add it as a note so we’re communicating in line with the official status.

**Pull request merged**
