### PR TITLE
Add Capture One

### PR DESCRIPTION
**Pull request by j-delaney**
Only comments I could find by them were from their Twitter

### CODE REVIEW

**Comment by mloupe** [comment]
Capture One 20 appears to be working with no issues on Rosetta

**Comment by ThatGuySam** [comment]
@mloupe Great! Let's do a screenshot we can use as a source link

Be sure to include the App, Activity Monitor showing the app details, and About this Mac so we can see the exact OS version. 

You can find an Activity Monitor example on #176

**Comment by mloupe** [comment]
capture one 20  Apple Silicon

Is this good?

**Comment by ThatGuySam** [comment]
@mloupe That's perfect!!

* [Capture One](https://www.captureone.com/en/download-trial) - ✳️ Yes, works via Rosetta 2 - [Source](https://github.com/ThatGuySam/doesitarm/pull/130#issuecomment-736183868)

Category: Photo and Graphic Tools

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Pull request merged**
