### PR TITLE
Archicad

### LINKED ISSUE #126: ArchiCAD
**The official name of the app**
Archicad

**Proposed App Status**
🚫 Not yet supported only works on Intel-based Macs

**Related Issue Tracker Link or discussion**
https://archicad-talk.graphisoft.com/viewtopic.php?p=312614
https://www.reddit.com/r/ArchiCAD/comments/hsjs6l/archicad_and_macos_armtransition/

**An Official App Download Link**
https://graphisoft.com/solutions/products/archicad

**Additional context**
If you find a better source for upcoming ARM support, it would be nice!

### PR DESCRIPTION
**Pull request by antoinerousseau**
#### Open Questions and Pre-Merge TODOs
- [x] Keeps list alphabetical. 
- [x] Matches Standard App Line Format. 
- [x] App status is clearly stated. 
- [x] App status is consistent with already used verbiage. 

Fixes #126.

Also created a new "3D and architecture" section, and fixed "Social and communication" title level.

### CODE REVIEW

**Comment by ThatGuySam** [comment]
I like the new category. 

Looks Good!

**Comment by tudy25** [comment]
ArchiCAD 24 works via Rosetta 2 - tested with a base M1 Macbook Pro.

**Comment by antoinerousseau** [comment]
@tudy25 wow great to know! is it as fast? faster? slower?

**Comment by tudy25** [comment]
Unfortunately this Mac is my friend's and I tested this remotely through Teamviewer, so everything I was seeing was choppy, but he told me the 3D was smooth af in ArchiCAD when I was panning around (it is a pretty big, complex project - my diploma actually - lots of 3D stuff being processed on the screen)... but overall I would have to say the performance was great, even impressive, considering it's not native for M1 and the 3D viewport is in OpenGL afaik. I only tested v24 but I would assume v23 works too.
In AutoCAD 2021 I asked him to zoom in/out of a very big and detailed .dwg and he said the animation was basically flawless (my gaming/rendering desktop PC is a bit choppy in this aspect!). I really don't know what Autodesk means by "not supported on Apple Silicon"... it works.
Now, I can't comment on the long-term stability but I'll have my M1 Air next week and I'll do a thorough testing.

**Comment by antoinerousseau** [comment]
Perfect! Looking forward to reading your feedback once you have your own M1 :)

**Comment by antoinerousseau** [comment]
I also wonder whether paying for 16 GB of RAM instead of 8 would make a big difference or not, given the latest benchmarks of other software...

**Comment by ThatGuySam** [comment]
@antoinerousseau If you or someone you know wants to post benchmarks we can link to them for people

**Comment by antoinerousseau** [comment]
@tudy25 have you been able to try Archicad for yourself on your new M1? :)

**Comment by ThatGuySam** [comment]
@antoinerousseau Here's a review of Archicad on the M1 from Youtube: 
https://www.youtube.com/watch?v=H7zLQgY65fs

**Comment by ThatGuySam** [comment]
@antoinerousseau Scratch that, I just realized the guy in that video doesn't even have an M1 and doesn't actually test it. 

We'll keep an eye out for a video and add it when we find one

**Comment by tudy25** [comment]
> @tudy25 have you been able to try Archicad for yourself on your new M1? :)

Yes! Sorry, for the late reply! So I've tested it myself but I'm not really impressed with the performance honestly - my previous Windows laptop, a Huawei Matebook D15 (Ryzen 3500U + 8GB), was much smoother opening up even really big, intensive projects and being essentially locked at 60fps in the 3D, this while having a much weaker APU (around 3000pts in Geekbench while plugged in and with a fan! + weaker graphics, Vega 8 is good but not on the level of M1). On the Air, ArchiCAD is slowish and the 3D window dips to 20-30 fps with larger projects - it just doesn't feel responsive or snappy. Yesss, I know on the M1 it's Rosetta doing the work but even with Rosetta it should plenty fast. GRAPHISOFT really needs to work their ass off and take advantage of Apple Silicon, they said in their official blog post that in 2022 there will be a native, complete version which seems unjustifiably long. AutoCAD works fine but again not as fast as I would like. Otherwise, optimized apps are shockingly responsive and fast, battery is outstanding, 8GB seems to act like 16GB,  the screen is gorgeous as we've come to expect from a retina MacBook, the laptop is light and portable - the Air is finally amazing in terms of value!

**Comment by antoinerousseau** [comment]
@tudy25 thanks a lot for this feedback!

**Comment by antoinerousseau** [comment]
I opened #463 to update the app status

**Comment by antoinerousseau** [comment]
Also: https://isapplesiliconready.com/app/Archicad

**Comment by ThatGuySam** [comment]
Cool website. Update is live! 

https://doesitarm.com/app/archicad/

**Pull request merged**
