### PR TITLE
Audacity now has native arm64 support.

### PR DESCRIPTION
**Pull request by elvey**

### CODE REVIEW

**Comment by elvey** [comment]
Interesting workflow I'm not familiar with.  My first time seeing a message like this, and on my first pull request to this repository.  I'll hold off - would seem appropriate for someone to step in and review (sanity check) my work prior to deployment even if this is just documentation. (I suppose I'll re-review it in a bit if no one acts on it for a while.)


> The Deployment for commit [a192cd4](https://github.com/ThatGuySam/doesitarm/commit/a192cd46d99d51368c266f39db347f7bf7253125) on pull request [ThatGuySam/doesitarm#952](https://github.com/ThatGuySam/doesitarm/pull/952) is awaiting authorization.
> As a member of the Sam Carlton Creative Team on Vercel, you are asked to [review the pull request](https://github.com/ThatGuySam/doesitarm/pull/952) and authorize this Deployment afterwards.

**Comment by ThatGuySam** [comment]
Thanks for the PR! 

I updated the verbiage to be a little evergreen so it's not incorrect later on and reformated the links so the Does It ARM bot can read the and add them to the site.

**Comment by ThatGuySam** [comment]
Update is now live! 

https://doesitarm.com/app/audacity

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by elvey** [comment]
Cool! Doh, I misspelled nightly. Just noticed.

**Pull request merged**
